### PR TITLE
Parse definitions from OVAL report

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by ares** [comment]
needs rebase now

**Review by akofink — APPROVED** [review]
Looks great, thanks! I think it needs a rebase before merge

**Comment by xprazak2** [comment]
Rebased

**Review by akofink — APPROVED** [review]
Thanks, @xprazak2!

**Comment by ares** [comment]
Thanks @xprazak2 and @akofink, merging!

**Pull request merged**
